/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */
#include <iostream>
using namespace std;

int fib(int n)
{
    if (n <= 1)
    {
        return n;
    }
    return fib(n - 1) + fib(n - 2);
}
int main()
{
    int fib(), temp1, temp2, sum = 0;
    for (int i = 0; i < 100; i++)
    {
        fib(i) = temp1;
        if (temp1 % 2 == 0)
            {
                temp2 = temp1;
                sum += temp2;
            }
    }
    cout << "THe sum is " << sum;

    return 0;
}